import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

const jost_init = Jost({ subsets: ["latin"], variable: "--font-jost" });

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost_init.variable}`}>{children}</body>
    </html>
  );
}
